version: '3'

services:  
  i386:
    build:
      context: ./
      args:
        ARCH: i386
        WX_VER: 3.0.3
    container_name: 'build_i386'
    stdin_open: true
    tty: true
    restart: unless-stopped
  amd64:
    build: 
      context: ./
      args:
        ARCH: amd64
        WX_VER: 3.0.3
    container_name: 'build_amd64'
    stdin_open: true
    tty: true    
    restart: unless-stopped
  armhf:
    build:
      context: ./
      args:
        ARCH: armhf
        WX_VER: 3.0.3
    container_name: 'build_armhf'
    stdin_open: true
    tty: true    
    restart: unless-stopped
  arm64:
    build:
      context: ./
      args:
        ARCH: arm64
        WX_VER: 3.0.3
    container_name: 'build_arm64'
    stdin_open: true
    tty: true
    restart: unless-stopped
  win32:
    build:
      context: ./
      args:
        ARCH: win32
        WX_VER: 3.0.3
    container_name: 'build_win32'
    stdin_open: true
    tty: true
    restart: unless-stopped
  win64:
    build:
      context: ./
      args:
        ARCH: win64
        WX_VER: 3.0.3
    container_name: 'build_win64'
    stdin_open: true
    tty: true
    restart: unless-stopped
