version: '3'

services:  
  i386:
    build:
      context: ./linux
      args:
        ARCH: i386
    container_name: 'build_i386'
    stdin_open: true
    tty: true
    restart: unless-stopped
  amd64:
    build: 
      context: ./linux
      args:
        ARCH: amd64
    container_name: 'build_amd64'
    stdin_open: true
    tty: true    
    restart: unless-stopped
  armhf:
    build:
      context: ./linux
      args:
        ARCH: armhf
    container_name: 'build_armhf'
    stdin_open: true
    tty: true    
    restart: unless-stopped
  arm64:
    build:
      context: ./linux
      args:
        ARCH: arm64
    container_name: 'build_arm64'
    stdin_open: true
    tty: true
    restart: unless-stopped
  win32:
    build:
      context: ./windows
      args:
        ARCH: win32
    container_name: 'build_win32'
    stdin_open: true
    tty: true
    restart: unless-stopped
  win64:
    build:
      context: ./windows
      args:
        ARCH: win64
    container_name: 'build_win64'
    stdin_open: true
    tty: true
    restart: unless-stopped
  osx:
    build:
      context: ./osx
      args:
        ARCH: osx
    container_name: 'build_osx'                                                                                                                                  
    stdin_open: true                                                                                                                                               
    tty: true                                                                                                                                                      
    restart: unless-stopped 
